### ISSUE TITLE
Problem with the "Filter" function

### ISSUE THREAD

**Issue by T-Shilov** [qvarforth/trackdirect#38]
Hello, dear Per,

I am very glad that you have updated the software platform for your Track Direct, respect! :-)
It now runs significantly faster and uses fewer resources.

A small error has appeared in the new version of Track Direct - the 'Filter' function does not work correctly: it does not display the selected icon.
Please fix this.

Best regards, 
Nicholas

**Comment by US1GHQ** [comment]
I confirm this bug to, the i press Filter, all stations is disappears, also heatmap gone away, when i reset filter all stations return.
Sorry for my English.

**Comment by qvarforth** [comment]
Thank you for reminding me about this problem (it is the same problem as the one reported in #30). I will try to find time to fix it as soon as possible.

**Comment by F4FXL** [comment]
Not sure if this is also related to this issue, but specifying filters on the URL also fails. Map stays empty.
https://aprsdirect.de/?sname=F4FXL&center=48.825,7.6047&zoom=12
https://aprsdirect.de/?snamelist=F4FXL,F5KAV-3&center=48.825,7.6047&zoom=12

**Comment by radi242** [comment]
Hi, indeed looks like filter function has been fixed. However for me it looks now there is a problem with displaying icons/aprs symbols. Example:

![image](https://github.com/qvarforth/trackdirect/assets/16956637/56a430fb-1220-49b4-a758-61dd099b1c96)

Could you please take a look at it in some spare time? If a separate Issue ticket is needed for it, please let me know.

**Comment by qvarforth** [comment]
Hi @radi242
It looks like you are using one of the APRS-IS sites, it is correct that they are based on the code from this github repo, but that error is probably related to that specific site. Please contact the maintainer of that site (I'm the maintainer of gliderradar.com, so for that site I can help you directly).

PS. The filter feature probably doesn't work on that site unless whoever maintains that site was extremely quick to deploy it (or fixed it themselves earlier).

**Comment by radi242** [comment]
I'm using a site operated by myself, so yes, I tried to be extremely quick here :) and indeed, deployed that updated code. It's located at https://144800.xyz. 

I think I found the source of the problem: running git clone on updated code leaves directory trackdirect/htdocs/public/symbols with missing symbol-*.png files. I have manually copied them from the old copy and now it works correctly.

**Comment by F4FXL** [comment]
I tested @radi242 updated site. The filters work on Chrome but Firefox crashes/freezes.
[https://144800.xyz/?snamelist=F4FXL,F5KAV-3&center=48.8556,7.6987&zoom=13](url)

**Comment by T-Shilov** [comment]
Hello, dear Per,

Unfortunately, your long-awaited corrections did not bring the desired result. 
I tried using Firefox 102.15.0 esr (64 bit) and Chromium 116.0.5845.140 (official build, built on Debian 11.7, running on Debian 11.7 (64 bit), I cleared the cache of both browsers. 
But the error remained the same :-(
